# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hotoo' do
    use_frameworks!
    pod 'SDWebImage'
    pod 'ReactiveObjC'
    pod 'MJRefresh'

end
